import { Product, Project, Certificate, BlogPost, Testimonial } from "./types";

export const CURRENCY_RATES = {
  USD: 1,
  EUR: 0.92,
  CNY: 7.24,
};

export const CURRENCY_SYMBOLS = {
  USD: "$",
  EUR: "€",
  CNY: "¥",
};

export const TRANSLATIONS = {
  en: {
    brandName: "MAISON ELITE",
    tagline: "Premium Furniture Manufacturing For Global Brands",
    subtagline: "Custom Furniture Solutions For Hotels, Villas, Apartments, Retail & Commercial Projects",
    viewCollection: "View Collection",
    requestQuote: "Request Quote",
    yearsExp: "Years Experience",
    countriesExported: "Countries Exported",
    projectsCompleted: "Projects Completed",
    factoryArea: "SQM Factory Area",
    productionCapacity: "Annual Container Capacity",
    theEliteStandard: "The Elite Standard",
    eliteStandardDesc: "We bridge the gap between visionary architectural design and flawless execution. Our vertically integrated manufacturing ensures uncompromising quality at global scale.",
    factoryDirect: "Factory Direct Pricing",
    factoryDirectDesc: "Eliminate middlemen with our comprehensive 20,000 sqm production facility, ensuring optimal project margins.",
    oemOdm: "OEM & ODM Mastery",
    oemOdmDesc: "From custom sketches to full-scale production runs, our engineering team brings complex hospitality and residential designs to life.",
    rigorousQc: "Rigorous Quality Control",
    rigorousQcDesc: "Multi-stage inspection protocols from wood curing to final packaging guarantee every piece meets international luxury standards.",
    allCollections: "Curated Collections",
    allCollectionsDesc: "Discover our mastery across diverse architectural, hospitality, and residential spaces.",
    products: "Products",
    projects: "Projects",
    factory: "Factory Tour",
    certifications: "Certifications",
    blog: "Blog & Insights",
    about: "About Us",
    contact: "Contact us",
    quickView: "Quick View",
    addToQuote: "Add to Request",
    addedToQuote: "In Inquiry",
    whatsappInquiry: "WhatsApp Inquiry",
    compare: "Compare",
    wishlist: "Wishlist",
    inquireForPricing: "Inquire for Pricing",
    searchPlaceholder: "Search collections or products...",
    showResultCount: "Showing {count} elite designs",
    sortBy: "Sort by",
    newest: "Newest Arrivals",
    priceHighToLow: "Price: High to Low",
    priceLowToHigh: "Price: Low to High",
    material: "Material",
    style: "Style",
    priceRange: "Price Group",
    allProducts: "All Products",
    description: "Description",
    specifications: "Specifications",
    materialsUsed: "Materials",
    faq: "FAQ",
    reviews: "Reviews",
    relatedProducts: "Related Elite Designs",
    packagingDetails: "Packaging Specifications",
    shippingInfo: "International Shipping Support",
    moq: "Minimum Order Quantity (MOQ)",
    productionLeadTime: "Production & Delivery Lead Time",
    customizationOptions: "Customization Services",
    dimensions: "Dimensions",
    factoryOverview: "Manufacturing Excellence",
    factoryDesc: "State-of-the-art 20,000 SQM facility in the heart of China's high-end furniture cluster, combining German precision machinery with hand-finished craftsmanship.",
    quoteRequestForm: "B2B Quote Request",
    submitForm: "Submit Inquiry",
    fullName: "Full Name",
    emailAddress: "Business Email",
    whatsappNumber: "WhatsApp (with Country Code)",
    companyName: "Company / Firm Name",
    message: "Inquiry details / Project requirements",
    submittedSuccess: "Thank you for contacting Maison Elite. A dedicated Senior Project Manager will reach out within 12 hours with detailed pricing, technical spec sheets, and material sample boards.",
    exitTitle: "Looking for something bespoke?",
    exitSubtitle: "Download our 2026 Architectural Catalog containing over 500+ customized modern, European, and neoclassical hotel project CAD blocks & high-res images.",
    downloadCatalog: "Download 2026 Catalog PDF",
    exitCloseName: "Continue Browsing",
    comparisonTitle: "Product Comparison",
    comparisonEmpty: "No products added for comparison. Select 'Compare' on product detail or list cards.",
  },
  zh: {
    brandName: "佐爵傲立 | MAISON ELITE",
    tagline: "甄选匠心 · 全球高端品牌家具制造商",
    subtagline: "为五星级酒店、高端别墅、雅奢公寓、高级零售和商业地产提供定制化家具全案集成方案",
    viewCollection: "浏览臻选系列",
    requestQuote: "获取工程报价",
    yearsExp: "年家具制造经验",
    countriesExported: "全球出口国家",
    projectsCompleted: "大型工程项目案例",
    factoryArea: "平米现代化工厂",
    productionCapacity: "年集装箱产能",
    theEliteStandard: "奢华品质标准",
    eliteStandardDesc: "我们架起了先锋建筑设计与无瑕制造执行之间的桥梁。高度垂直一体化的智能物流与大师工艺系统确保满足全球工程项目的严苛要求。",
    factoryDirect: "工厂直供优势",
    factoryDirectDesc: "拥有20,000平米大规模生产基地，消除中间环节，确保为您留出最佳的商业利润与开发预算。",
    oemOdm: "OEM / ODM 深度定制",
    oemOdmDesc: "从概念手稿、三维深深化到大批量产，我们的资深工程团队让最杰出的设计创意完美落地。",
    rigorousQc: "严苛质量控制体系",
    rigorousQcDesc: "从原材料烘干、含水率测试到最后拼装打包，执行五维多重检测确保品质媲美欧洲顶级古典工艺。",
    allCollections: "策展艺术空间",
    allCollectionsDesc: "探索我们在大平层住宅、皇家别墅、奢华酒店等不同艺术空间中呈现的丰腴美学。",
    products: "产品中心",
    projects: "项目全案",
    factory: "智能工厂",
    certifications: "资质证书",
    blog: "名家洞察",
    about: "关于品牌",
    contact: "联系我们",
    quickView: "快速预览",
    addToQuote: "加入询价车",
    addedToQuote: "已在询价列表中",
    whatsappInquiry: "WhatsApp 联络",
    compare: "产品比对",
    wishlist: "收藏夹",
    inquireForPricing: "获取定制价",
    searchPlaceholder: "输入品类、材质或空间搜索...",
    showResultCount: "展示 {count} 项高奢设计",
    sortBy: "排序方式",
    newest: "新品推荐",
    priceHighToLow: "价格：由高到低",
    priceLowToHigh: "价格：由低到高",
    material: "材质选择",
    style: "美学风格",
    priceRange: "价格梯度",
    allProducts: "全部品类",
    description: "详尽介绍",
    specifications: "详尽参数",
    materialsUsed: "核心用料",
    faq: "常见问题解答",
    reviews: "合作评价",
    relatedProducts: "为您推荐的配套产品",
    packagingDetails: "国际防撞包装规范",
    shippingInfo: "全球多式联运支持",
    moq: "最低起订量（MOQ）",
    productionLeadTime: "货期与物流周期",
    customizationOptions: "定制化专项服务",
    dimensions: "规格尺寸",
    factoryOverview: "生产品质与溯源",
    factoryDesc: "位于中国高端家具制造集群核心区的20,000平米智能化厂房。引进德国精工木工机床，并保留大师上手磨刷等古建筑复刻式非遗工艺。",
    quoteRequestForm: "B2B 方案询价单",
    submitForm: "提交需求",
    fullName: "您的姓名",
    emailAddress: "企业电子邮箱",
    whatsappNumber: "手机 / WhatsApp",
    companyName: "企业 / 事务所名称",
    message: "定制或询价需求 / 预期交期 / 项目详情",
    submittedSuccess: "您的工程询价已安全提交至 Maison Elite 全球大客户部。我们的资深驻外项目经理会在12小时内向您发送CAD图纸、技术规格表和专属面料皮料样板包。",
    exitTitle: "正在寻找专属深度定制服务？",
    exitSubtitle: "立即下载 Maison Elite 2026 年度建筑与室内设计专属高清画册，内含500多款现成高奢模型、CAD模块及实景图。",
    downloadCatalog: "下载 2026 画册 (PDF 格式)",
    exitCloseName: "继续浏览",
    comparisonTitle: "产品比对",
    comparisonEmpty: "比对列表为空。您可以在产品中心将心仪的产品添加至多角度比对。",
  },
  fr: {
    brandName: "MAISON ELITE",
    tagline: "Manufacture de Meubles Haut de Gamme",
    subtagline: "Solutions de Mobilier sur Mesure pour Hôtels, Villas, Appartements de Luxe et Projets Commerciaux",
    viewCollection: "Découvrir la Collection",
    requestQuote: "Demander un Devis",
    yearsExp: "Ans d'Expérience",
    countriesExported: "Pays d'Exportation",
    projectsCompleted: "Projets Réalisés",
    factoryArea: "m² de Surface Usine",
    productionCapacity: "Capacité de Conteneurs par An",
    theEliteStandard: "Le Standard d'Élite",
    eliteStandardDesc: "Nous comblons le fossé entre la conception architecturale visionnaire et l'exécution impeccable. Notre usine verticalement intégrée garantit une qualité sans compromis.",
    factoryDirect: "Tarification Direct Usine",
    factoryDirectDesc: "Éliminez les intermédiaires grâce à notre site de production de 20 000 m², garantissant des marges optimales pour vos projets.",
    oemOdm: "Maîtrise OEM & ODM",
    oemOdmDesc: "Des croquis personnalisés à la production de masse, notre équipe d'ingénieurs donne vie à vos concepts résidentiels et hôteliers les plus complexes.",
    rigorousQc: "Contrôle Qualité Rigoureux",
    rigorousQcDesc: "Des protocoles d'inspection rigoureux garantissent que chaque meuble respecte les normes et exigences du luxe international.",
    allCollections: "Collections Curatées",
    allCollectionsDesc: "Découvrez notre savoir-faire unique à travers différents projets d'envergure internationale.",
    products: "Produits",
    projects: "Projets",
    factory: "L'Usine",
    certifications: "Certifications",
    blog: "Actualités & Blog",
    about: "À Propos",
    contact: "Contact",
    quickView: "Aperçu Rapide",
    addToQuote: "Ajouter au Devis",
    addedToQuote: "Dans la Liste d'Inquiry",
    whatsappInquiry: "WhatsApp Direct",
    compare: "Comparer",
    wishlist: "Favoris",
    inquireForPricing: "Obtenir le prix d'usine",
    searchPlaceholder: "Rechercher un produit...",
    showResultCount: "Affichage de {count} créations exclusives",
    sortBy: "Trier par",
    newest: "Nouveautés",
    priceHighToLow: "Prix: Élevé à Faible",
    priceLowToHigh: "Prix: Faible à Élevé",
    material: "Matériau",
    style: "Style",
    priceRange: "Gamme de Prix",
    allProducts: "Tous les Produits",
    description: "Description",
    specifications: "Spécifications",
    materialsUsed: "Matériaux",
    faq: "FAQ",
    reviews: "Avis Clients",
    relatedProducts: "Produits Associés",
    packagingDetails: "Spécifications d'Emballage",
    shippingInfo: "Transport & Logistique de Export",
    moq: "Quantité Minimum (MOQ)",
    productionLeadTime: "Délai de Production",
    customizationOptions: "Options de Personnalisation",
    dimensions: "Dimensions",
    factoryOverview: "Excellence Industrielle",
    factoryDesc: "Un complexe de 20 000 m² à la pointe de la technologie, unissant les machines allemandes de haute précision et la finition hautement artisanale.",
    quoteRequestForm: "Formulaire de Demande B2B",
    submitForm: "Envoyer ma Demande",
    fullName: "Nom Complet",
    emailAddress: "Email Professionnel",
    whatsappNumber: "Numéro de WhatsApp",
    companyName: "Nom de l'Entreprise",
    message: "Détails de l'Inquiry / Spécifications de Projet",
    submittedSuccess: "Merci de votre intérêt pour Maison Elite. Un chef de projet senior prendra contact avec vous sous 12 heures pour vous envoyer des dossiers techniques de prix et nos échantillons.",
    exitTitle: "Besoin d'un mobilier exclusif?",
    exitSubtitle: "Téléchargez notre catalogue d'architecture 2026 contenant plus de 500 modèles de meubles, blocs DAO/CAD et inspirations pour vos créations.",
    downloadCatalog: "Télécharger le Catalogue PDF 2026",
    exitCloseName: "Continuer la Navigation",
    comparisonTitle: "Comparaison des Produits",
    comparisonEmpty: "Aucun meuble dans votre tableau de comparaison pour le moment.",
  },
  it: {
    brandName: "MAISON ELITE",
    tagline: "Produzione di Mobili di Lusso",
    subtagline: "Soluzioni d'Arredo su Misura per Hotel, Ville, Appartamenti Prestazioni e Spazi Commerciali",
    viewCollection: "Vedi Collezione",
    requestQuote: "Richiedi Preventivo",
    yearsExp: "Anni di Esperienza",
    countriesExported: "Paesi Esportati",
    projectsCompleted: "Progetti Completati",
    factoryArea: "mq di Area Produttiva",
    productionCapacity: "Capacità di Container Annuale",
    theEliteStandard: "Lo Standard d'Élite",
    eliteStandardDesc: "Colleghiamo l'estro del design d'eccellenza con la perfezione manifatturiera. La nostra filiera integrata assicura finiture di lusso insuperabili.",
    factoryDirect: "Prezzi Diretti dalla Fabbrica",
    factoryDirectDesc: "Grazie alla nostra struttura di 20.000 mq, offriamo preventivi di eccezionale convenienza per i tuoi progetti contract hôtelier.",
    oemOdm: "Soluzioni OEM e ODM",
    oemOdmDesc: "Dal disegno dei dettagli allo sviluppo della produzione interna, plasmando i materiali per realizzare arredamenti di inimitabile pregio.",
    rigorousQc: "Controllo Qualità Rigoroso",
    rigorousQcDesc: "Ogni singola fase, dall'asciugatura dei legni al packaging internazionale, rispetta i massimi parametri di certificazione globale.",
    allCollections: "Collezioni Storiche",
    allCollectionsDesc: "Sfoglia la nostra maestria per arredare aree lounge, ville esclusive e contesti urbani contemporanei.",
    products: "Prodotti",
    projects: "Progetti Contract",
    factory: "La Fabbrica",
    certifications: "Certificazioni",
    blog: "Stile & Focus",
    about: "Brand & Storia",
    contact: "Contattaci",
    quickView: "Anteprima Rapida",
    addToQuote: "Aggiungi al Devis",
    addedToQuote: "In Lista di Richiesta",
    whatsappInquiry: "Invia WhatsApp",
    compare: "Confronta",
    wishlist: "Salvati",
    inquireForPricing: "Chiedi Listino Prezzi",
    searchPlaceholder: "Cerca mobili o finiture...",
    showResultCount: "Mostrando {count} creazioni d'élite",
    sortBy: "Ordina per",
    newest: "Novità",
    priceHighToLow: "Prezzo: Alto-Basso",
    priceLowToHigh: "Prezzo: Basso-Alto",
    material: "Materiale",
    style: "Stile d'Arredo",
    priceRange: "Fascia di Prezzo",
    allProducts: "Tutti i Prodotti",
    description: "Descrizione",
    specifications: "Specifiche Tecniche",
    materialsUsed: "Materiali Utilizzati",
    faq: "Domande Frequenti",
    reviews: "Dicono di Noi",
    relatedProducts: "Prodotti Correlati",
    packagingDetails: "Specifiche di Imballaggio",
    shippingInfo: "Supporto Logistico Doganale",
    moq: "Quantità Minima Ordinabile (MOQ)",
    productionLeadTime: "Tempi di Produzione",
    customizationOptions: "Opzioni di Personalizzazione",
    dimensions: "Dimensioni",
    factoryOverview: "Competenza Artigianale",
    factoryDesc: "Sito di produzione d'elite su 20.000 mq. Coniughiamo alta ingegneria a controllo numerico con rifinitura interamente eseguita a mano.",
    quoteRequestForm: "Richiesta Preventivo B2B",
    submitForm: "Invia Richiesta",
    fullName: "Nome e Cognome",
    emailAddress: "Email Aziendale",
    whatsappNumber: "Numero WhatsApp",
    companyName: "Nome Società / Studio",
    message: "Dettagli del Progetto / Richieste Particolari",
    submittedSuccess: "Grazie per aver scelto Maison Elite. Il tuo Project Manager dedicato prenderà in carico la richiesta per inviarti quotazioni complete, file CAD e tavole materiche entro 12 ore.",
    exitTitle: "Desideri arredi unici?",
    exitSubtitle: "Scarica subito il catalogo architettonico Maison Elite 2026. Catalogo con oltre 500 arredi dettagliati pronti per i tuoi progetti di interni.",
    downloadCatalog: "Scarica Catalogo PDF 2026",
    exitCloseName: "Continua la Navigazione",
    comparisonTitle: "Confronto Prodotti",
    comparisonEmpty: "Nessun prodotto selezionato per il confronto.",
  },
};

export const PRODUCTS_DATA: Product[] = [
  {
    id: "prod-1",
    name: "European Leather Sofa",
    category: "Living Room Furniture",
    subtitle: "Heritage Collection • Solid Oak & Premium Aniline Leather",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLsBz3ep05lB5vhi7QJxJzRI3apyQmkGJ3J2VCAHIwQ2oQS0RULxJxAzZchaqvSjnMF-N4mObjirw2XE9o4EbuUKWixOVePl3nvJfvFtGZnIztkr8prdwAu2s6KQJt8Z1PBgdZoBDE5E7UeB1KJ7PKz4R3WejIEMFuoc-dy0VPjZ3hjimAp-v2lZ8A1HQmyT-OHoUANRN0T5HthrrAbQh1Zmix7yvyrC1vhOajllEpwaueFb8h6X0HZLVg",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLsBz3ep05lB5vhi7QJxJzRI3apyQmkGJ3J2VCAHIwQ2oQS0RULxJxAzZchaqvSjnMF-N4mObjirw2XE9o4EbuUKWixOVePl3nvJfvFtGZnIztkr8prdwAu2s6KQJt8Z1PBgdZoBDE5E7UeB1KJ7PKz4R3WejIEMFuoc-dy0VPjZ3hjimAp-v2lZ8A1HQmyT-OHoUANRN0T5HthrrAbQh1Zmix7yvyrC1vhOajllEpwaueFb8h6X0HZLVg",
      "https://lh3.googleusercontent.com/aida/AP1WRLtd9yRRw_x9lv0Rb2P3zY9Bm-9RdDCdn47HM-5nWB0qC3s_Cn3-BnXACRoJ1THrF8du5GiicM2qMSe-bYJO3UwDy2gU5mgKjsSMOC-kVVOwas0nru9Xi8zm6wPyVzs5teca5I5axM4Nu95ncUjWyEMz-qesOCn3WEZeU26vSMUipAvm8H_OMKzxPZPiWDJ32R13w3JiEJi2p7V6w1PC-ACmk4srgJPZW6Kx8x6ltKtrXs5cgaJcNblXLDM",
    ],
    materials: ["Solid White Oak Frame", "Grain-Corrected Italian Aniline Leather", "High-Density Resilient Foam", "Brushed Brass Accents"],
    dimensions: "W 240cm x D 105cm x H 85cm",
    colors: ["Classic Cognac", "Obsidian Black", "Smoked Umber", "Parchment Cream"],
    customizationOptions: ["Custom sizes available up to 400cm", "Alternate leather types (Nubuck, Semi-Aniline)", "Carved wood finish tint (Dark Roast, Antique Honey, Ebonized)"],
    productionTime: "30-40 Days depending on quantity",
    moq: "5 Units (For customized sample runs, please contact global helpdesk)",
    packagingDetails: "5-Layer heavy-duty export carton box, custom EPE protective foam padding corner protection, wrapped in thick protective canvas bag, fortified on a solid wooden pallet cage.",
    shippingInfo: "FOB Shenzhen / Ningbo Port. Complete commercial B2B documents supplied (CO, Form E, fumigation certification, test reports). Fully insured Ocean & Air freight coordination to EU/USA/GCC.",
    description: "Taking cues from classical mid-century European designs, this sofa merges structural oak skeletons with hand-buffered Italian aniline leather. Every seam is double-stitched using UV-resistant premium upholstery threads, promising minimal stretch over extensive commercial cycles.",
    specifications: {
      "Structural Frame": "Multi-layered kiln-dried Russian Pine with Solid White Oak structural legs",
      "Upholstery Base": "Sinuous arch steel coil springs with high-density nylon webbing suspension grids",
      "Seat Cushion Fill": "45kg/m³ high-density pure polyurethane memory foam cocooned in goose down wraps",
      "Hardware Fitting": "Authentic stainless steel underlying bolts with brushed gold anti-oxidation floor glides"
    },
    priceApprox: 3400,
  },
  {
    id: "prod-2",
    name: "Palace Fabric Sofa",
    category: "Living Room Furniture",
    subtitle: "Versailles Series • Hand-carved Mahogany & Silk Damask",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLT3SyDuQB0fF-DSUNGCy9IAwpPwTou1Cp659a1aIKpP3iF-JxArySrR2jbT0RwPwQVzxpcuJm-CdF54A7-oX9GF8z57pMAjBA6IjOkyKcndEenpbF7ek16_r_Yfe86d3h1Ydk_M31uukFx6h_bCwiSER0zc6nfT9IUEdNVydBx_eugWGgAFjxHd1aqFq0FsBPGRS64s70f0iTRQ1nRQYw64jJLIRJnDA5e2aasZkCl1j73JzyjNapweg8",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLT3SyDuQB0fF-DSUNGCy9IAwpPwTou1Cp659a1aIKpP3iF-JxArySrR2jbT0RwPwQVzxpcuJm-CdF54A7-oX9GF8z57pMAjBA6IjOkyKcndEenpbF7ek16_r_Yfe86d3h1Ydk_M31uukFx6h_bCwiSER0zc6nfT9IUEdNVydBx_eugWGgAFjxHd1aqFq0FsBPGRS64s70f0iTRQ1nRQYw64jJLIRJnDA5e2aasZkCl1j73JzyjNapweg8",
      "https://lh3.googleusercontent.com/aida/AP1WRLsBz3ep05lB5vhi7QJxJzRI3apyQmkGJ3J2VCAHIwQ2oQS0RULxJxAzZchaqvSjnMF-N4mObjirw2XE9o4EbuUKWixOVePl3nvJfvFtGZnIztkr8prdwAu2s6KQJt8Z1PBgdZoBDE5E7UeB1KJ7PKz4R3WejIEMFuoc-dy0VPjZ3hjimAp-v2lZ8A1HQmyT-OHoUANRN0T5HthrrAbQh1Zmix7yvyrC1vhOajllEpwaueFb8h6X0HZLVg",
    ],
    materials: ["Hand-carved Genuine Premium Mahogany Wood", "Belgian Silk Damask Jacquard Thread", "24K Gold Leaf Foil Guilding Finish"],
    dimensions: "W 255cm x D 110cm x H 90cm",
    colors: ["Imperial Teal/Gold Accent", "Royal Blue/Silver Accent", "Parchment/Champagne Accent"],
    customizationOptions: ["Custom upholstery material selection including client's own fabric (COM)", "Frame gilding customization in Rose Gold or Platinum plating", "Softness factor modification (Plush, Balanced, Firm)"],
    productionTime: "45-55 Days due to intense manual woodcarving labor",
    moq: "3 Units",
    packagingDetails: "Thick wrap protective bubble roll, dense EPE corner guards, cardboard envelope box, and custom-made heavy plywood crate box with clear export branding marks.",
    shippingInfo: "FOB Ningbo. Certified fumigation included. Heavy-duty ocean sea container shipping is highly recommended due to high volumetric weight.",
    description: "An archival masterpiece of French luxury design, with handcrafted ornate details meticulously carved into AAA-grade mahogany by master woodcarvers with over 30 years of generational expertise. Accented with genuine 24K gold foil pressed directly into the wood grain.",
    specifications: {
      "Wood Structure": "Solid kiln-dry AAA Philippine Mahogany (less than 10% moisture content to prevent splitting)",
      "Carving Technique": "100% hand-sculpted sculptural relief motifs without resin or plastic molds",
      "Upholstery Material": "High-durability silk & satin brocade with high Martindale friction count rating (>40,000 double rubs)",
      "Internal Springs": "Individual coil springs tied by hand with linen cord in a heavy eight-way knot configuration"
    },
    priceApprox: 4800,
  },
  {
    id: "prod-3",
    name: "Luxury Sofa Set",
    category: "Living Room Furniture",
    subtitle: "Milano Minimalist Series • Leather Upholstered & Brushed Brass",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLt-aiCNPqh3kUmAM0UkKdbxUJa0C-Ofw_E-qlCpU7DGEUMKNjrQ2w5YdtTyLVWN23RKpyKgfMXveCBwE3wYHNV1Bv-9H8CctSgqJk-pWuNj5r2NqBEs6CiVBpuLJYnhDqVvwI0gP_-sBpbUSd6l06-M2iGPTPAOhwHqgmKDquTJ31iwoS47CfMFtm-Cbhc7D7cMvQLHkblayid3ePc5zR8o3tM70Kk6TdG5Y0t85m7g2glXPjFjl3MLyZg",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLt-aiCNPqh3kUmAM0UkKdbxUJa0C-Ofw_E-qlCpU7DGEUMKNjrQ2w5YdtTyLVWN23RKpyKgfMXveCBwE3wYHNV1Bv-9H8CctSgqJk-pWuNj5r2NqBEs6CiVBpuLJYnhDqVvwI0gP_-sBpbUSd6l06-M2iGPTPAOhwHqgmKDquTJ31iwoS47CfMFtm-Cbhc7D7cMvQLHkblayid3ePc5zR8o3tM70Kk6TdG5Y0t85m7g2glXPjFjl3MLyZg",
      "https://lh3.googleusercontent.com/aida/AP1WRLtd9yRRw_x9lv0Rb2P3zY9Bm-9RdDCdn47HM-5nWB0qC3s_Cn3-BnXACRoJ1THrF8du5GiicM2qMSe-bYJO3UwDy2gU5mgKjsSMOC-kVVOwas0nru9Xi8zm6wPyVzs5teca5I5axM4Nu95ncUjWyEMz-qesOCn3WEZeU26vSMUipAvm8H_OMKzxPZPiWDJ32R13w3JiEJi2p7V6w1PC-ACmk4srgJPZW6Kx8x6ltKtrXs5cgaJcNblXLDM"
    ],
    materials: ["Premium Italian Nubuck Leather", "Ultra-thin Brushed Brass Sled Legs", "Cold-molded Foam Core"],
    dimensions: "W 220cm x D 98cm x H 78cm",
    colors: ["Minimalist Alabaster White", "Warm Taupe Gray", "Saddle Tan", "Sage Green"],
    customizationOptions: ["Custom lengths (3-seater or XL 4-seater dynamic configurations)", "Matching architectural club chairs and benches"],
    productionTime: "25-30 Days using expedited manufacturing lanes",
    moq: "5 Units",
    packagingDetails: "Protected via thick cardboard side armor panels, individual heat-sealed polybagging to block humidity, custom fitted honeycomb corner brackets, seated inside wooden structural crate containers.",
    shippingInfo: "FOB Shenzhen or Shanghai. International freight services, drop-deck unloading available on site for contract developments.",
    description: "Celebrating architectural restraint and geometric balance. Bathed in soft, natural light coming from large windows, this sleek white nubuck leather sofa displays a low, grounding posture making it ideal for penthouses and luxury corporate villas.",
    specifications: {
      "Sled Leg Structure": "Laser-cut 316 grade stainless steel plates electroplated in gold satin oil coating",
      "Core Cushioning": "Variable density cold-cured foam containing high-resilience memory polymers",
      "Frame Assembly": "Engineered multi-layered steel strut framework guaranteeing persistent structural load over 250kg"
    },
    priceApprox: 2900,
  },
  {
    id: "prod-4",
    name: "Baroque Luxe Sofa",
    category: "Living Room Furniture",
    subtitle: "Florentine Archive Series • Deep Navy Royal Velvet",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLtd9yRRw_x9lv0Rb2P3zY9Bm-9RdDCdn47HM-5nWB0qC3s_Cn3-BnXACRoJ1THrF8du5GiicM2qMSe-bYJO3UwDy2gU5mgKjsSMOC-kVVOwas0nru9Xi8zm6wPyVzs5teca5I5axM4Nu95ncUjWyEMz-qesOCn3WEZeU26vSMUipAvm8H_OMKzxPZPiWDJ32R13w3JiEJi2p7V6w1PC-ACmk4srgJPZW6Kx8x6ltKtrXs5cgaJcNblXLDM",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLtd9yRRw_x9lv0Rb2P3zY9Bm-9RdDCdn47HM-5nWB0qC3s_Cn3-BnXACRoJ1THrF8du5GiicM2qMSe-bYJO3UwDy2gU5mgKjsSMOC-kVVOwas0nru9Xi8zm6wPyVzs5teca5I5axM4Nu95ncUjWyEMz-qesOCn3WEZeU26vSMUipAvm8H_OMKzxPZPiWDJ32R13w3JiEJi2p7V6w1PC-ACmk4srgJPZW6Kx8x6ltKtrXs5cgaJcNblXLDM",
    ],
    materials: ["Solid Ebonized Walnut Wood Frame", "Royal Navy Blue Mohair Velvet Upholstery", "Steel Coil Springs"],
    dimensions: "W 235cm x D 102cm x H 88cm",
    colors: ["Deep Navy Royal Blue", "Crimson Cardinal Velvet", "Ebonized Charcoal", "Emerald Forest Green"],
    customizationOptions: ["Custom wood framing types (Mahogany, Oak, Cherry Wood)", "Fringe trim customization on the lower hem"],
    productionTime: "40-45 Days",
    moq: "3 Units",
    packagingDetails: "Wrap-around protective foam padding, protective fabric bag, wood crate enclosure.",
    shippingInfo: "FOB Ningbo / Shanghai Ports. Complete commercial invoices, certificates of origin and customs paperwork managed on-demand.",
    description: "An incredibly dramatic, deep navy blue velvet sofa framed by thick, hand-carved ebonized walnut wood moldings. Built to capture Florentine palace archives, bringing ancient craftsmanship into modern high-rise villa penthouses.",
    specifications: {
      "Carving Style": "100% Traditional Italian hand-carved baroque patterns",
      "Wood Framework": "Individually selected high-density walnut lumber cured for 180 days to stabilize moisture",
      "Upholstery Softness": "Thick plush seating utilizing high-density fiber wraps over inner spring pockets"
    },
    priceApprox: 4500,
  },
  {
    id: "prod-5",
    name: "Emperor's Tufted Bed",
    category: "Bedroom Furniture",
    subtitle: "Majestic Suite Series • Tufted Velvet Headboard & Walnut",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLu_lUkkBrTBKDBAnBzpOvWeRJpTch6khQRlSRUnNEWLsGnbp4QRn5Rm6-0t_31l3duZ8F_EZVF469f7BNNK0_MnFX5sPNFDxfwe87e4i1H0c7ZhXnkEmNvvHM9Gtn0JK4ciH0ul24A-VnMmInooYILfZGe1L8D-l3s6e9vE-IKtVPAs5Zn1doluu-uQZNjgUKM0cBBcjEDtAAa5ngb2cbnkz5xj49LfuUSVwFS1FRCE8w7xJFfWvfd7PA",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLu_lUkkBrTBKDBAnBzpOvWeRJpTch6khQRlSRUnNEWLsGnbp4QRn5Rm6-0t_31l3duZ8F_EZVF469f7BNNK0_MnFX5sPNFDxfwe87e4i1H0c7ZhXnkEmNvvHM9Gtn0JK4ciH0ul24A-VnMmInooYILfZGe1L8D-l3s6e9vE-IKtVPAs5Zn1doluu-uQZNjgUKM0cBBcjEDtAAa5ngb2cbnkz5xj49LfuUSVwFS1FRCE8w7xJFfWvfd7PA"
    ],
    materials: ["Kiln-Dry Solid Sapele Mahogany Frame", "Royal Italian Tufted Cotton Velvet", "Gold Foil Outlines"],
    dimensions: "W 210cm x L 230cm x H 165cm (Headboard)",
    colors: ["Esterel Burgundy", "Royal Sapphire Blue", "Champagne Gold Slate"],
    customizationOptions: ["Available in California King, Eastern King, and Custom Sizes", "Headboard height extendable up to 220cm", "Built-in hidden B2B multi-standard power sockets & LED warm reading lights"],
    productionTime: "35-45 Days",
    moq: "5 Units",
    packagingDetails: "Knock-down structural configuration. Headboard, footboard, and side railings packed in separate heavy triple-wall cardboard boxes, wrapped individually in protective non-woven blankets.",
    shippingInfo: "FOB Ningbo / Shenzhen. Complete structural installation hardware, step-by-step videos, and expert engineering layouts for luxury hotel installation teams provided.",
    description: "Command respect in any luxury hotel project or residential estate. High headboard containing hand-tufted royal cotton velvet framed by thick mahogany molding finished in detailed gold leaves.",
    specifications: {
      "Slat Support Grid": "Individually curved multi-ply soundless solid wood slats with heavy double-row middle metal supports",
      "Headboard Padding": "Flame-retardant B1-certified (UK/US hotel compliance code) high density padding",
      "Leg Materials": "Carved heavy European beech wood finished in high-gloss piano black lacquering"
    },
    priceApprox: 3900,
  },
  {
    id: "prod-6",
    name: "Palazzo Dining Table Set",
    category: "Dining Furniture",
    subtitle: "Carrara Elite Series • Gold Metal Pedestals & Suede Chairs",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLuWnuAXqfqqmQtG2-2atMD2bdh0vS-3NY5gUqo5i2vLo8T6cFESXsTbHHV4_VvLmHuAD5Ps4hLeGj9rr42wNWIDpl51VlCwGt4nK3W-NdnfOjANpaErYGS-yNEYNsLddxGbtld73jUJ21Qyi30LbuJNLVND4lfMTr3s2ULov4D6ylMXEW8VYR3JPPp9QCNgC_28grPT0Sfl9OkKrxaHKsUBtGKWV4uXkwuIGUYxPfU7UOLuCPEHjnDSpa8",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLuWnuAXqfqqmQtG2-2atMD2bdh0vS-3NY5gUqo5i2vLo8T6cFESXsTbHHV4_VvLmHuAD5Ps4hLeGj9rr42wNWIDpl51VlCwGt4nK3W-NdnfOjANpaErYGS-yNEYNsLddxGbtld73jUJ21Qyi30LbuJNLVND4lfMTr3s2ULov4D6ylMXEW8VYR3JPPp9QCNgC_28grPT0Sfl9OkKrxaHKsUBtGKWV4uXkwuIGUYxPfU7UOLuCPEHjnDSpa8"
    ],
    materials: ["Premium Italian Carrara White Marble", "Solid cast structural aluminum table legs", "Brushed Brass Ring Profiles"],
    dimensions: "Table: L 220cm x W 110cm x H 75cm, Chairs: Standard Size",
    colors: ["Polished Carrara White / Brass Base", "Nero Marquina Black / Carbon Base"],
    customizationOptions: ["Custom table dimensions up to 340cm length", "Lazy Susan rotation center integration for imperial banquets", "10 different chairs custom catalog pairings"],
    productionTime: "30-35 Days",
    moq: "2 Sets (1 Table + 6/8 Chairs per set)",
    packagingDetails: "Marble top nested in a dense custom steel framework, padded via high density expanding polystyrene foam layers, wrapped under tight wood crate armor.",
    shippingInfo: "FOB Xiamen or Ningbo. Specialized heavy marble handling equipment suggestions, shipping guidelines, and insurance policies on-demand.",
    description: "The ultimate dining experience designed to handle commercial Michelin stars and high-end residential clients. Features a stunning book-matched Carrara marble slab hovering over a heavy fluid sculptured pedestal structure.",
    specifications: {
      "Stone Thickness": "30mm solid genuine natural stone slab, treated with deep stain resistant invisible sealers",
      "Pedestal Weight": "Highly heavy solid cast aluminum alloy, powder-baked in luxury satin brass",
      "Chair Upholstery": "High Martindale suede material wrapped around a soundproof seamless bent-plywood shell"
    },
    priceApprox: 5200,
  },
  {
    id: "prod-7",
    name: "Vogue Lounge Armchair",
    category: "Hotel Furniture",
    subtitle: "Atelier Signature Series • Velvet Wrap & Brushed Gold Frame",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLvQCXPlIQC7xQ4lD5BIwAEkoJ-bTuVwpQgMOMv9bxstnnJ5P4yGdpRJxxHjMTHA_zI8C4044yHVV7NvewLkzKBOuTkNngCDUUjYPo4xbgbFLr867tCw8J2vtpPCL96AK7ojbcjbuDfZhZIBqkLugLDxBxn-ZWicmDyLynsRFPna5qflfkrHb2cavCjpxC_lF8P-2InxkAjGbvTBkwSPzdLe9U4OUPaDCwjJdSr7uE7eJTthtJtoEepwgUM",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLvQCXPlIQC7xQ4lD5BIwAEkoJ-bTuVwpQgMOMv9bxstnnJ5P4yGdpRJxxHjMTHA_zI8C4044yHVV7NvewLkzKBOuTkNngCDUUjYPo4xbgbFLr867tCw8J2vtpPCL96AK7ojbcjbuDfZhZIBqkLugLDxBxn-ZWicmDyLynsRFPna5qflfkrHb2cavCjpxC_lF8P-2InxkAjGbvTBkwSPzdLe9U4OUPaDCwjJdSr7uE7eJTthtJtoEepwgUM"
    ],
    materials: ["Seamless 304 Stainless Steel Ring", "Textured boucle plush, or royal velvet", "Gold leaf accents"],
    dimensions: "W 90cm x D 85cm x H 80cm",
    colors: ["Classic Emerald Green", "Boucle Pearl White", "Saffron Yellow", "Burnt Siena"],
    customizationOptions: ["Custom swivel core setup with high weight-limit bearings", "Logo branding engraving on the steel ring", "Alternative custom textures"],
    productionTime: "20-25 Days",
    moq: "10 Units (Optimal pricing tiers for hospitality bulk orders)",
    packagingDetails: "Shipped fully assembled. Packed inside protective soft structural bubble jackets, double-strength B2B cartons, and stacked upright on thick wooden crates.",
    shippingInfo: "FOB Shenzhen. High volume packing optimization templates provided to minimize ocean cargo container waste costs is our specialty.",
    description: "Designed for premium global hotel lobbies, members-only clubs, and executive suites. This armchair offers a dramatic high-contrast circular silhouette wrapping the body in deep, tactile luxury.",
    specifications: {
      "Steel Treatment": "Thick 304 stainless steel frame highly hand-polished to mirror finish then vacuum vapor titanium color-plated",
      "Ergonomics": "Bespoke lumbar cushion curvature, providing highly comfortable orthopedic support during long loungings",
      "Understructure": "Fitted with non-marking soft rubber feet covers protecting luxury flooring"
    },
    priceApprox: 1200,
  }
];

export const PROJECTS_DATA: Project[] = [
  {
    id: "proj-1",
    title: "Ritz-Carlton Presidential Suites",
    category: "Hotel Projects",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLvQCXPlIQC7xQ4lD5BIwAEkoJ-bTuVwpQgMOMv9bxstnnJ5P4yGdpRJxxHjMTHA_zI8C4044yHVV7NvewLkzKBOuTkNngCDUUjYPo4xbgbFLr867tCw8J2vtpPCL96AK7ojbcjbuDfZhZIBqkLugLDxBxn-ZWicmDyLynsRFPna5qflfkrHb2cavCjpxC_lF8P-2InxkAjGbvTBkwSPzdLe9U4OUPaDCwjJdSr7uE7eJTthtJtoEepwgUM",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLvQCXPlIQC7xQ4lD5BIwAEkoJ-bTuVwpQgMOMv9bxstnnJ5P4yGdpRJxxHjMTHA_zI8C4044yHVV7NvewLkzKBOuTkNngCDUUjYPo4xbgbFLr867tCw8J2vtpPCL96AK7ojbcjbuDfZhZIBqkLugLDxBxn-ZWicmDyLynsRFPna5qflfkrHb2cavCjpxC_lF8P-2InxkAjGbvTBkwSPzdLe9U4OUPaDCwjJdSr7uE7eJTthtJtoEepwgUM"
    ],
    description: "Bespoke custom furniture supply for 45 newly renovated Presidential and Executive Suites of a top hospitality brand, featuring hand-carved classical details, gold leaf inlays, and ultra-high durability fire-safety fabrics.",
    furnitureSupplied: [
      "Custom Grand Baroque Sofas",
      "Presidential King Bed Ensembles",
      "Hand-carved Mahogany Lounge Desk Cabinets",
      "Satin Brass Accented Lounge Chairs"
    ],
    timeline: "90 Days from CAD approvals to delivery on site",
    clientRequirements: "Bespoke French neoclassical details, meeting fire-safety standards (BS-7176 Medium Hazard), premium natural wood matching, and high weight-load requirements.",
    finalResult: "Flawless on-time delivery. Zero failures reported during safety audits, with the hotel recording a 35% growth in suite booking premiums due to the exceptional luxurious look and feel.",
    location: "Ritz-Carlton, London & New York"
  },
  {
    id: "proj-2",
    title: "Côte d'Azur Premium Villa",
    category: "Villa Projects",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLtkRwjyGF6cZIyclVPFM0Dxp0Xt0_Nij6ff4xtzVnnuwGFabNwdtqUu8OQBwze_nLN6symsVpPN-Hg-O5KXtZCzeVQMvABSjSiao9lfEJXPMee4ZnB0-z22qXnCUHhAcx1u6zQAKL7efE_QogqsHF8w8JX42mbVkweUjOt_N93QdVty0tMgkTKTz8xypHwhJRCVGwwVOqQt45eIZHtTPcuBXKrqr_BnXmIiF8-D-hSnmUYRkt0hKDU4pgI",
    gallery: [
      "https://lh3.googleusercontent.com/aida/AP1WRLtkRwjyGF6cZIyclVPFM0Dxp0Xt0_Nij6ff4xtzVnnuwGFabNwdtqUu8OQBwze_nLN6symsVpPN-Hg-O5KXtZCzeVQMvABSjSiao9lfEJXPMee4ZnB0-z22qXnCUHhAcx1u6zQAKL7efE_QogqsHF8w8JX42mbVkweUjOt_N93QdVty0tMgkTKTz8xypHwhJRCVGwwVOqQt45eIZHtTPcuBXKrqr_BnXmIiF8-D-hSnmUYRkt0hKDU4pgI"
    ],
    description: "Multi-room design and furniture manufacture for a breathtaking 1200 SQM private villa in southern France, mixing clean Italian marble dining with rich warm tufted bedroom setups.",
    furnitureSupplied: [
      "Palazzo Carrara Dining Table with 12 custom suede chairs",
      "Atelier Boucle Swivel Lounge Chairs",
      "Emperor King Bed custom sets with matching bedside panels",
      "Custom outdoor weather-resistant teak wood patio lounge furniture"
    ],
    timeline: "60 Days production, 25 days shipping & white-glove setup",
    clientRequirements: "Minimalist exterior profiles combined with warm tactile interior fabrics, matching custom dimensions matching specific architectural floor plans.",
    finalResult: "Successfully delivered. The primary designer commented: 'Maison Elite's capacity of matching high-end Italian furniture details at direct B2B factory pricing saved the owner over EUR 180,000 compared to sourcing directly in Milan.'",
    location: "Nice, Côte d'Azur, France"
  }
];

export const CERTIFICATIONS_DATA: Certificate[] = [
  {
    id: "cert-1",
    title: "ISO 9001:2015 Quality Management System",
    issuer: "SGS International Inspection Group",
    year: "2025",
    type: "Quality certificates",
    imageLabel: "ISO 9001 Audit Seal"
  },
  {
    id: "cert-2",
    title: "FSC CoC Forest Stewardship Council System Certificate",
    issuer: "German Forest Alliance & BVQI",
    year: "2026",
    type: "Export certificates",
    imageLabel: "100% Sustainably Sourced Wood"
  },
  {
    id: "cert-3",
    title: "Standard BS 5852 / CAL-133 Flame Retardant Audited",
    issuer: "Intertek Testing Laboratory",
    year: "2025",
    type: "Product certifications",
    imageLabel: "US/UK Fire-Safety Certified"
  },
  {
    id: "cert-4",
    title: "Gold-Class Supplier & Custom Factory Audit",
    issuer: "TÜV Rheinland Group",
    year: "2025",
    type: "Factory audits",
    imageLabel: "TÜV Rheinland Approved"
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Why High-End Hotel Developers Are Sourcing Direct From Luxury Chinese Manufacturers",
    summary: "How vertically integrated CNC engineering, generational carving talent, and global timber sourcing are allowing luxury hotel chains to bypass design-house markups without losing an ounce of Italian refinement.",
    content: "For decades, the standard procurement script for ultra-luxury hotel projects was simple: specify in London, purchase in Milan, and swallow the 300% design-house markups. But a quiet, structural transformation is restructuring high-end hotel procurement...\n\n### The Shift to Vertically Integrated Engineering\nToday's world-class hotel developers require more than just aesthetic furniture. They require technical precision. The current crop of premium Chinese manufacturers like Maison Elite run completely integrated 20,000 sqm facilities combining elite CNC machinery imported from Germany with deep, multigenerational master woodcarving artisans.\n\n### Material Sourcing Rigor\nTo successfully achieve this, wood sourcing is global: Solid White Oak is imported from North American sustainable forests, ebonized walnut from Europe, and mahogany from Southeast Asian certified plantations. Woods are cured for a mandatory 180 days in computer-supervised dry kilns, guaranteeing that moisture content matches the client's destination hemisphere (reducing splitting risks in London winters, or warping in Dubai summers).\n\n### Conforming to Global Fire Regulations\nCommercial projects require strict certification. Sourcing direct means that fabrics, foam cores, and internal linings comply perfectly with UK BS 5852 or USA CAL-133 flame-retardant safety standards, supported directly by genuine test reports from SGS or Intertek.",
    category: "Hotel Furniture",
    date: "May 15, 2026",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLvQCXPlIQC7xQ4lD5BIwAEkoJ-bTuVwpQgMOMv9bxstnnJ5P4yGdpRJxxHjMTHA_zI8C4044yHVV7NvewLkzKBOuTkNngCDUUjYPo4xbgbFLr867tCw8J2vtpPCL96AK7ojbcjbuDfZhZIBqkLugLDxBxn-ZWicmDyLynsRFPna5qflfkrHb2cavCjpxC_lF8P-2InxkAjGbvTBkwSPzdLe9U4OUPaDCwjJdSr7uE7eJTthtJtoEepwgUM",
    author: "Richard Vance (Principal Hospitality Designer)",
    readTime: "6 Min Read",
    slug: "why-hotel-developers-source-direct-china-luxury"
  },
  {
    id: "blog-2",
    title: "Curing & Calibration: The Crucial Steps Behind Split-Proof Solid Hardwood Furniture",
    summary: "Cracks, splitting, and joint failures are the ultimate enemies of contract furniture. We discuss how scientific kiln-drying processes maintain wood moisture below 8-10% to survive arctic cold and Sahara heat.",
    content: "Whether it is a heavy dining top in a New York luxury high-rise penthouse, or a massive mahogany headboard in a Cote d'Azur beach-front estate, wood moves. As relative humidity rises and falls throughout the seasons, natural timber expands and contracts. Left unmanaged, this will destroy wood joins, trigger visual cracks, and bubble premium lacquered finishes. Here is how Maison Elite solves this structural puzzle...\n\n### The Kiln Drying Science\nWhen raw logs enter our production yard, they contain up to 50% natural moisture content. Standard cheap furniture mills dry logs via simple outdoor stacking, taking several weeks to achieve a volatile 15-18% level. When placed inside central-heated modern penthouses, the dry winter air sucks this moisture away rapid-fire, causing wood splitting.\n\nAt Maison Elite, our logs undergo computer-controlled vacuum dry kilns with over 8 independent heating phases. We slowly program down moisture to exactly 8-10%. Only after achieving this calibrated percentage are wood blocks released to craftsmen.\n\n### Custom Hemisphere Calibration\nWe program the moisture target specifically based on the ship-to destination country. A villa project going to Riyadh requires woods with exceptionally low humidity (around 6-8%), while a hotel project in Singapore is stabilized at 12%. This guarantees structural stability of joins for decades to come, far bypassing cheap Alibaba alternatives.",
    category: "Manufacturing",
    date: "April 28, 2026",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLt9cTlAeDEeOmyi4pMWjlW9eVjxTI-DjG-qExBZF-7uifMbqDLaLtXhsGNP2pUUTIM0BEpX1OsmSwwn8UL2H-bM_xLGbqre6u9rfsKm6e3isu9WJvDUVmSNF5pAx5VAfBFLo8LxEi7EV080xYUYAC1_slPL1nOYJakfCg28e9L6jZ9LhunBimK4O1zzknf1ZRVi76AqMeaaDQ6LDg0on18GhbR8Py9tg7cvHn43GeszDHkkUWX8RzU4O0Q",
    author: "Guo Hong (Director of Timber Engineering)",
    readTime: "8 Min Read",
    slug: "curing-wood-calibration-preventing-furniture-splits"
  },
  {
    id: "blog-3",
    title: "The B2B Buyers' Guide: Auditing Furniture Factory Licenses and Quality Management Systems",
    summary: "How architects and hotel developers inspect genuine ISO 9001 certifications, raw material supply chains, compliance logs, and factory capabilities remotely to avoid B2B scams.",
    content: "Sourcing luxury residential and commercial contract furniture globally can be highly rewarding, but requires cautious B2B auditing processes. How do developers separate elite suppliers from simple middleman traders masquerading as direct factories? Follow this audit checklist...\n\n- **Check Factory Location Logs:** Genuine factories should occupy registered industrial parks, not residential clusters. Look for certifications validated by SGS, BVQI, or TÜV Rheinland.\n- **Verify Wood FSC Certificates:** Confirm that all timber can be traced back to sustainable legal logging. True manufacturers have a registered FSC chain-of-custody (CoC) number.\n- **Test Report Authenticity:** Always ask for genuine test reports for foam core densities and fabric flame retardancy, stamped by certified laboratories like Intertek.",
    category: "Buying Guides",
    date: "March 12, 2026",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLT9cTlAeDEeOmyi4pMWjlW9eVjxTI-DjG-qExBZF-7uifMbqDLaLtXhsGNP2pUUTIM0BEpX1OsmSwwn8UL2H-bM_xLGbqre6u9rfsKm6e3isu9WJvDUVmSNF5pAx5VAfBFLo8LxEi7EV080xYUYAC1_slPL1nOYJakfCg28e9L6jZ9LhunBimK4O1zzknf1ZRVi76AqMeaaDQ6LDg0on18GhbR8Py9tg7cvHn43GeszDHkkUWX8RzU4O0Q",
    author: "Elena Rostov (International Sourcing Consultant)",
    readTime: "5 Min Read",
    slug: "b2b-buyers-guide-auditing-furniture-factory-licenses"
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Alistair Sterling",
    role: "Senior Partner & Director of Architecture",
    company: "Sterling & Croft Design Firm, London",
    quote: "Maison Elite completely outperformed expectations. They manufactured and shipped custom French Baroque luxury seating for our boutique resort project in Monaco. The gold leaf detailing is pristine, and the BS 5852 compliance reports made hotel clearance a breeze. It's safe to say we saved 40% on sourcing compared to luxury houses in Milan, with zero compromise on visual luxury.",
    rating: 5
  },
  {
    id: "test-2",
    name: "Sophia Martinez",
    role: "Lead Interior Designer",
    company: "Marriott Luxury Group Procurement, Americas",
    quote: "With hospitality projects, MOQ, shipping reliability, and custom CAD blueprint reproduction are everything. Maison Elite's engineers translated our detailed DWG drawings into clean physical mahogany components effortlessly. Their packaging is bulletproof - every item arrived in perfect condition. They are our trusted manufacturing core for premium lobby developments.",
    rating: 5
  },
  {
    id: "test-3",
    name: "Yousef Al-Mansoori",
    role: "Managing Director",
    company: "Amara Estates & Villa Developers, Dubai",
    quote: "We sourced complete marble dining sets and custom leather couches for our luxury royal villas in Palm Jumeirah. Maison Elite's custom dry kilns calibrated the hardwood to 6% moisture - meaning no cracks despite local Middle East climate. Absolutely outstanding craftsmanship and world-class B2B export coordination.",
    rating: 5
  }
];

export const FACTORY_DEPARTMENTS = [
  {
    name: "Advanced Precision Millwork Workshop",
    description: "Equipped with state-of-the-art German CNC 5-axis routers. Computerized laser measurement calibrates wood cuts down to 0.05mm, making sure every modular tongue-and-groove joint aligns with architectural standards.",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLT9cTlAeDEeOmyi4pMWjlW9eVjxTI-DjG-qExBZF-7uifMbqDLaLtXhsGNP2pUUTIM0BEpX1OsmSwwn8UL2H-bM_xLGbqre6u9rfsKm6e3isu9WJvDUVmSNF5pAx5VAfBFLo8LxEi7EV080xYUYAC1_slPL1nOYJakfCg28e9L6jZ9LhunBimK4O1zzknf1ZRVi76AqMeaaDQ6LDg0on18GhbR8Py9tg7cvHn43GeszDHkkUWX8RzU4O0Q",
    highlights: ["German CNC Wood Router Systems", "High-frequency precision joinery bonding", "Calibrated laser wood calibration"]
  },
  {
    name: "Artisanal Hand-carving Atelier",
    description: "The soul of Maison Elite. Over 45 master woodcarvers with decades of generational training painstakingly sculpt mahogany, white oak, and walnut blocks directly by hand with specialized chisels, reproducing traditional Italian baroque molds.",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLtd9yRRw_x9lv0Rb2P3zY9Bm-9RdDCdn47HM-5nWB0qC3s_Cn3-BnXACRoJ1THrF8du5GiicM2qMSe-bYJO3UwDy2gU5mgKjsSMOC-kVVOwas0nru9Xi8zm6wPyVzs5teca5I5axM4Nu95ncUjWyEMz-qesOCn3WEZeU26vSMUipAvm8H_OMKzxPZPiWDJ32R13w3JiEJi2p7V6w1PC-ACmk4srgJPZW6Kx8x6ltKtrXs5cgaJcNblXLDM",
    highlights: ["100% Manual Hand Sculpting", "Legacy 24K Gold Leaf foil gilding", "Antique hand-rubbed finish polishing"]
  },
  {
    name: "Textile & High-Density Upholstery Assembly",
    description: "Where premium Italian aniline leather, boucle, and custom fabrics are hand-cut and tailored. Fabric lines are equipped with heavy multi-needle stitching systems and high density latex/polyurethane filling machines.",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLT9cTlAeDEeOmyi4pMWjlW9eVjxTI-DjG-qExBZF-7uifMbqDLaLtXhsGNP2pUUTIM0BEpX1OsmSwwn8UL2H-bM_xLGbqre6u9rfsKm6e3isu9WJvDUVmSNF5pAx5VAfBFLo8LxEi7EV080xYUYAC1_slPL1nOYJakfCg28e9L6jZ9LhunBimK4O1zzknf1ZRVi76AqMeaaDQ6LDg0on18GhbR8Py9tg7cvHn43GeszDHkkUWX8RzU4O0Q",
    highlights: ["Sinuous coil suspension grids", "High Martindale-rated fabric tailoring", "UK/USA Fire Safety Compliant assembly"]
  },
  {
    name: "Scientific Quality Testing & Lab",
    description: "Our dedicated testing center. Furniture samples undergo heavy cyclic load stress simulations, moisture evaluation trials, leather stretch stress parameters, and fabric color rub tests to guarantee lasting luxury.",
    image: "https://lh3.googleusercontent.com/aida/AP1WRLT9cTlAeDEeOmyi4pMWjlW9eVjxTI-DjG-qExBZF-7uifMbqDLaLtXhsGNP2pUUTIM0BEpX1OsmSwwn8UL2H-bM_xLGbqre6u9rfsKm6e3isu9WJvDUVmSNF5pAx5VAfBFLo8LxEi7EV080xYUYAC1_slPL1nOYJakfCg28e9L6jZ9LhunBimK4O1zzknf1ZRVi76AqMeaaDQ6LDg0on18GhbR8Py9tg7cvHn43GeszDHkkUWX8RzU4O0Q",
    highlights: ["Cyclic weight load testing systems", "Continuous moisture evaluations", "Salt spray tests for metal finishes"]
  }
];

export const BEFORE_AFTER_SHOWCASE = {
  title: "From Blueprints to Prestigious Reality",
  subtitle: "See how we transform formal CAD blueprints into flawless high-end furniture installations for world-class hotel contracts.",
  items: [
    {
      name: "Grand Ballroom Lounge Couch",
      project: "Monaco Grand Hotel & Casino",
      beforeLabel: "CAD Engineering Blueprints",
      beforeImage: "https://lh3.googleusercontent.com/aida/AP1WRLsBz3ep05lB5vhi7QJxJzRI3apyQmkGJ3J2VCAHIwQ2oQS0RULxJxAzZchaqvSjnMF-N4mObjirw2XE9o4EbuUKWixOVePl3nvJfvFtGZnIztkr8prdwAu2s6KQJt8Z1PBgdZoBDE5E7UeB1KJ7PKz4R3WejIEMFuoc-dy0VPjZ3hjimAp-v2lZ8A1HQmyT-OHoUANRN0T5HthrrAbQh1Zmix7yvyrC1vhOajllEpwaueFb8h6X0HZLVg", // Solid sketch/photo placeholder
      afterLabel: "Final Delivered Masterpiece",
      afterImage: "https://lh3.googleusercontent.com/aida/AP1WRLtd9yRRw_x9lv0Rb2P3zY9Bm-9RdDCdn47HM-5nWB0qC3s_Cn3-BnXACRoJ1THrF8du5GiicM2qMSe-bYJO3UwDy2gU5mgKjsSMOC-kVVOwas0nru9Xi8zm6wPyVzs5teca5I5axM4Nu95ncUjWyEMz-qesOCn3WEZeU26vSMUipAvm8H_OMKzxPZPiWDJ32R13w3JiEJi2p7V6w1PC-ACmk4srgJPZW6Kx8x6ltKtrXs5cgaJcNblXLDM", // Velvet sofa or similar beautiful final result
    }
  ]
};
export const FAQS_DATA = [
  {
    q: "How does Maison Elite prevent wood splitting during trans-ocean shipping & severe climate changes?",
    a: "We address this scientifically. Before crafting, all lumber spends 30-45 days in variable vacuum kilns reducing natural wood moisture to exactly 8-10% calibrated based on the destination. Shipments going to dry desert environments like Saudi Arabia are dried to 6-8%, while humid tropical countries are stabilized at 12%, eliminating wood expansion stress."
  },
  {
    q: "Do your furniture materials comply with commercial B2B hospitality safety codes?",
    a: "Absolutely. Maison Elite's fabrics and foams comply with major international contract fire safety regulations, including UK BS 5852 (Crib 5) standards and USA California Technical Bulletin 133 (CAL 133). Certifications from Intertek or SGS are provided with every contract."
  },
  {
    q: "What is your standard Minimum Order Quantity (MOQ) and sample lead time?",
    a: "Our typical project MOQ is 5 standard items, or a minimum room setup bundle. For customized OEM drafts, we can design specialized prototype sample pieces within 15-20 days. Full containers usually build within 30-45 days."
  },
  {
    q: "Can you manufacture furniture directly from custom CAD, DWG, or PDF interior design files?",
    a: "Yes. Our internal architectural team has 12 senior CAD drafters. We can parse DWG, PDF, and Revit models directly, generating factory-grade 1:1 structural drawings within 48 hours for client approval before cutting real wood."
  },
  {
    q: "What are your standard payment terms for wholesale B2B projects?",
    a: "Standard terms are 30% T/T deposit to begin production and material preparation, followed by 70% T/T balance payment prior to custom container loading. We provide detailed third-party SGS pre-shipment inspections and high-definition video walkthroughs before balance collection."
  }
];
